version: '3.8'

services:
  telegram-bot:
    image: nartay938/devops-telegram-bot:latest
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=botpassword
      - MYSQL_DB=bot_db
      - REDIS_HOST=redis
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped
    networks:
      - bot-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: botpassword
      MYSQL_DATABASE: bot_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - bot-network

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - bot-network

  adminer:
    image: adminer
    ports:
      - "8082:8080"
    depends_on:
      - mysql
    networks:
      - bot-network

volumes:
  mysql_data:
  redis_data:

networks:
  bot-network:
    driver: bridge
