apiVersion: v1
kind: Secret
metadata:
  name: bot-secrets
  namespace: telegram-bot
type: Opaque
data:
  TELEGRAM_TOKEN:  ODAxMzExODk3ODpBQUg1NkxIMTdDUzBORzBmUXl2MHpiaHQ4Q0FxNmhsYjlwUQ== # замените на base64 вашего токена
  MYSQL_PASSWORD: Ym90cGFzc3dvcmQ=   # botpassword в base64
